import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:news_app/model/news_model.dart';
import 'package:url_launcher/url_launcher.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  Autogenerated ar;
  var response;

  @override
  void initState() {
    super.initState();
    fetchNews();
  }

  Future<void> fetchNews() async {
    response = await http.get(
        "http://newsapi.org/v2/top-headlines?country=in&apiKey=e7cef96fc8cb4821969ad62e0767df33");
    var data = json.decode(response.body);
//    print(data);
    ar = Autogenerated.fromJson(data);
    setState(() {});
    print(ar.totalResults);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("News App"),
      ),
      body: Container(
        child: response != null
            ? ListView.builder(
                itemCount: ar.articles.length,
                itemBuilder: (context, index) {
                  return InkWell(
                    onTap: ()  {
                      openWebview(index);
                    },
                    child: Card(
                        child: ar.articles[index].urlToImage != null && ar.articles[index].title!=null
                            ? Container(
                          padding: EdgeInsets.all(5),
                              child: Column(
                                  children: [
                                    ClipRRect(
                                      borderRadius: BorderRadius.circular(20),
                                      child: Image.network(
                                          "${ar.articles[index].urlToImage}"),
                                    ),
                                    Padding(padding: EdgeInsets.all(10),),
                                    Text(
                                      "${ar.articles[index].title}",
                                      style: TextStyle(
                                          fontSize: 18,
                                          fontWeight: FontWeight.bold),
                                    ),
                                    Padding(padding: EdgeInsets.all(5),),
                                    Text("${ar.articles[index].description}"),
                                    Padding(padding: EdgeInsets.all(10),),
                                  ],
                                ),
                            )
                            : Container()),
                  );
                })
            : Center(child: CircularProgressIndicator()),
      ),
    );
  }

   openWebview(index)async {
     String url = ar.articles[index].url;
     if (await canLaunch(url))
     launch(url);
     else
     throw 'Can not launch';

   }
}
